INSERT into team(name, league) VALUES( "atlanta falcons", 'nfl');
INSERT into team(name, league) VALUES( "new england patriots", 'nfl');
INSERT into team(name, league) VALUES( "dallas cowboys", 'nfl');
INSERT into team(name, league) VALUES( "new york giants", 'nfl');
INSERT into team(name, league) VALUES( "pittsburgh steelers", 'nfl');
INSERT into team(name, league) VALUES( "denver broncos", 'nfl');
INSERT into team(name, league) VALUES( "san francisco giants", 'mlb');
INSERT into team(name, league) VALUES( "detroit tigers", 'mlb');
INSERT into team(name, league) VALUES( "new york yankees", 'mlb');
INSERT into team(name, league) VALUES( "boston red sox", 'mlb');
INSERT into team(name, league) VALUES( "oakland as", 'mlb');
INSERT into team(name, league) VALUES( "texas rangers", 'mlb');
INSERT into team(name, league) VALUES( "los angeles lakers", 'nba');
INSERT into team(name, league) VALUES( "los angeles clippers", 'nba');
INSERT into team(name, league) VALUES( "miami heat", 'nba');
INSERT into team(name, league) VALUES( "boston celtics", 'nba');
INSERT into team(name, league) VALUES( "oklahoma city thunder", 'nba');
INSERT into team(name, league) VALUES( "new york knicks", 'nba');
