INSERT into team(name, league, logourl) VALUES("atlanta falcons", 'nfl', '"atlanta_falcons.jpeg"');
INSERT into team(name, league, logourl) VALUES("new england patriots", 'nfl', '"new_england_patriots.jpeg"');
INSERT into team(name, league, logourl) VALUES("dallas cowboys", 'nfl', '"dallas_cowboys.jpeg"');
INSERT into team(name, league, logourl) VALUES("new york giants", 'nfl', '"new_york_giants.jpeg"');
INSERT into team(name, league, logourl) VALUES("pittsburgh steelers", 'nfl', '"pittsburgh_steelers.jpeg"');
INSERT into team(name, league, logourl) VALUES("denver broncos", 'nfl', '"denver_broncos.jpeg"');
INSERT into team(name, league, logourl) VALUES("san francisco giants", 'mlb', '"san_francisco_giants.jpeg"');
INSERT into team(name, league, logourl) VALUES("detroit tigers", 'mlb', '"detroit_tigers.jpeg"');
INSERT into team(name, league, logourl) VALUES("new york yankees", 'mlb', '"new_york_yankees.jpeg"');
INSERT into team(name, league, logourl) VALUES("boston red sox", 'mlb', '"boston_red_sox.jpeg"');
INSERT into team(name, league, logourl) VALUES("oakland as", 'mlb', '"oakland_as.jpeg"');
INSERT into team(name, league, logourl) VALUES("texas rangers", 'mlb', '"texas_rangers.jpeg"');
INSERT into team(name, league, logourl) VALUES("los angeles lakers", 'nba', '"los_angeles_lakers.jpeg"');
INSERT into team(name, league, logourl) VALUES("los angeles clippers", 'nba', '"los_angeles_clippers.jpeg"');
INSERT into team(name, league, logourl) VALUES("miami heat", 'nba', '"miami_heat.jpeg"');
INSERT into team(name, league, logourl) VALUES("boston celtics", 'nba', '"boston_celtics.jpeg"');
INSERT into team(name, league, logourl) VALUES("oklahoma city thunder", 'nba', '"oklahoma_city_thunder.jpeg"');
INSERT into team(name, league, logourl) VALUES("new york knicks", 'nba', '"new_york_knicks.jpeg"');
